# Generated by Django 5.1.6 on 2025-03-09 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_app', '0003_rename_title_book_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='title',
        ),
    ]
